### ISSUE TITLE
I have been using the WMii driver with weewx for a year with no problems. Want to access the hardware but Wee_device runs to using configuration file then returns to command prompt. This happens after a reboot and weewx not running. The WMii has a weatherlink connected to a serial to usb converter connected to a raspberry pi.

### ISSUE THREAD

**Issue by operaphile** [jardiamj/jardiamj#1]

**Comment by jardiamj** [comment]
Hi!

You submitted this on the wrong repository, this is my profile. You probably wanted to add this issue to the repository: https://github.com/jardiamj/wmII.
In regards to the issue, you cannot use `wee_device` with this driver since I didn't need it. I can look it up and see if it is not too hard to implement but can't promise anything.

**Comment by operaphile** [comment]
Sorry for the inconvenience. Have a good day.
